### ISSUE TITLE
Improving error message for wasm proposal

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/beaker#47] opened 2022-06-24 16:10 UTC
Hitting this error when using mainnet (an account with no funds on mainnet) test1.

```
beaker wasm proposal store-code --title "Mainner Contract" --description "Official Contract for" --signer-account test1 --network mainnet counter --gas 100000uosmo --gas-limit 100000
```

The expected result should be something about not having enough funds.
Output:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: serde parse error

Caused by:
    expected value at line 1 column 1

Location:
    /Users/web/.cargo/registry/src/github.com-1ecc6299db9ec823/flex-error-0.4.4/src/tracer_impl/eyre.rs:10:9

Caused by:
   0: serde parse error
   1: expected value at line 1 column 1

Location:
    /Users/web/.cargo/registry/src/github.com-1ecc6299db9ec823/cosmrs-0.7.1/src/tx/raw.rs:34:12', /Users/web/.cargo/registry/src/github.com-1ecc6299db9ec823/beaker-0.0.4/src/support/cosmos.rs:246:77
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by iboss-ptk** [comment] 2022-07-01 03:06
@daniel-farina I can't reproduce this on my machine. Could you try again and include stack trace? (with `RUST_BACKTRACE=1`)



![Image](https://user-images.githubusercontent.com/6301078/176815605-a7a1c50f-1840-45a6-b859-e01e9e1a3721.png)

**Comment by iboss-ptk** [comment] 2022-08-12 03:37
Close this issue for now since can't be reproduced, please open new issue if you have found it again.

**Closed by iboss-ptk** 2022-08-12 03:37 UTC
Labels: ⚙️ task
